#!/usr/bin/env python3
#
# This file is part of photoframe (https://github.com/mrworf/photoframe).
#
# photoframe is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# photoframe is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with photoframe.  If not, see <http://www.gnu.org/licenses/>.
#
import os
import json
import re
import shutil
import subprocess
import threading
from pathlib import Path

from modules.path import path
import logging

class sysconfig:
  # Everything after this line in config.txt belongs to the active display driver and
  # is rewritten by drivers.activate()
  DRIVER_MARKER = '### DO NOT EDIT BEYOND THIS COMMENT, IT\'S AUTOGENERATED BY PHOTOFRAME ###'

  # Held while config.txt is read and rewritten, so two settings changes at once
  # cannot overwrite each other. Reentrant: the writers call replaceConfigFile().
  CONFIG_LOCK = threading.RLock()

  @staticmethod
  def _fsync(name):
    # Sync a file or directory to disk; a failure is logged, the data is still written
    try:
      fd = os.open(name, os.O_RDONLY)
      try:
        os.fsync(fd)
      finally:
        os.close(fd)
    except OSError as e:
      logging.warning(f'Could not sync {name} to disk: {e}')

  @staticmethod
  def replaceConfigFile(content):
    # Replace config.txt so that a power cut never leaves it missing or half-written
    # (#111): keep the first version as config.txt.original, write and sync the new
    # file, swap it in with a single rename, then sync config.txt itself and its
    # directory. On FAT the swapped file's directory entry is only written when the
    # file is synced; until then it points at the old file's freed clusters.
    target = str(path.CONFIG_TXT)
    with sysconfig.CONFIG_LOCK:
      try:
        if not os.path.exists(f'{target}.original'):
          shutil.copy2(target, f'{target}.original')
          sysconfig._fsync(f'{target}.original')
        with open(f'{target}.new', 'w') as f:
          f.write(content)
          f.flush()
          os.fsync(f.fileno())
        os.replace(f'{target}.new', target)
      except Exception:
        logging.exception(f'Failed to update {target}')
        return False
      # The new content is in place; now make its directory entry durable
      sysconfig._fsync(target)
      sysconfig._fsync(os.path.dirname(target) or '.')
      return True

  @staticmethod
  def _getConfigFileState(key):
    if os.path.exists(path.CONFIG_TXT):
      with open(path.CONFIG_TXT, 'r') as f:
        for line in f:
          clean = line.strip()
          if clean == '':
            continue
          if clean.startswith(f'{key}='):
            _, value = clean.split('=', 1)
            return value
    return None

  @staticmethod
  def _changeConfigFile(key, value):
    with sysconfig.CONFIG_LOCK:
      if not os.path.exists(path.CONFIG_TXT):
        return False
      configline = f'{key}={value}'
      with open(path.CONFIG_TXT, 'r') as f:
        lines = f.read().splitlines()
      # Keep the setting above the display driver's section, which a driver change
      # rewrites (#111). Copies below it, left by older versions, are moved up.
      stripped = [line.strip() for line in lines]
      if sysconfig.DRIVER_MARKER in stripped:
        cut = stripped.index(sysconfig.DRIVER_MARKER)
        head, tail = lines[:cut], lines[cut:]
        tail = [line for line in tail if not line.strip().startswith(f'{key}=')]
      else:
        head, tail = lines, []
      found = False
      for i, line in enumerate(head):
        if line.strip().startswith(f'{key}='):
          head[i] = configline
          found = True
      if not found:
        head.append(configline)
      return sysconfig.replaceConfigFile('\n'.join(head + tail) + '\n')

  @staticmethod
  def usesVC4DisplayDriver():
    # True with the KMS driver (vc4-kms-v3d) or the fake-KMS driver (vc4-fkms-v3d).
    # Under KMS display_rotate has no effect on screen (#109); under fake KMS the
    # framebuffer keeps the display's unrotated size. Either way photoframe must not
    # swap width and height for display_rotate.
    if os.path.exists(path.CONFIG_TXT):
      with open(path.CONFIG_TXT, 'r') as f:
        for line in f:
          clean = line.strip()
          if clean.startswith('dtoverlay=vc4-kms-v3d') or clean.startswith('dtoverlay=vc4-fkms-v3d'):
            return True
    return False

  @staticmethod
  def _displayRotateQuarterTurns():
    # display_rotate may be written in hex with flip bits (e.g. 0x10002);
    # the low two bits are the rotation in quarter turns
    state = sysconfig._getConfigFileState('display_rotate')
    if state is None:
      return 0
    state = state.strip()
    try:
      value = int(state, 16) if state.lower().startswith('0x') else int(state)
    except ValueError:
      value = -1
    if value < 0:
      logging.warning(f'Ignoring display_rotate={state} in {path.CONFIG_TXT}, it is not a valid value')
      return 0
    return value & 3

  @staticmethod
  def isDisplayRotated():
    return sysconfig._displayRotateQuarterTurns() in (1, 3)

  @staticmethod
  def getDisplayOrientation():
    return sysconfig._displayRotateQuarterTurns() * 90

  @staticmethod
  def setDisplayOverscan(enable):
    if enable:
      return sysconfig._changeConfigFile('disable_overscan', '0')
    else:
      return sysconfig._changeConfigFile('disable_overscan', '1')

  @staticmethod
  def isDisplayOverscan():
    state = sysconfig._getConfigFileState('disable_overscan')
    if state is not None:
      return state == '0'
    return True # Typically true for RPi

  @staticmethod
  def setDisplayOrientation(deg):
    return sysconfig._changeConfigFile('display_rotate', str(int(deg/90)))

  @staticmethod
  def _app_opt_load():
    if os.path.exists(path.OPTIONSFILE):
      lines = {}
      with open(path.OPTIONSFILE, 'r') as f:
        for line in f:
          key, value = line.strip().split('=', 1)
          lines[key.strip()] = value.strip()
      return lines
    return None

  @staticmethod
  def _app_opt_save(lines):
    with open(path.OPTIONSFILE, 'w') as f:
      for key in lines:
        f.write(f'{key}={lines[key]}\n')

  @staticmethod
  def setOption(key, value):
    lines = sysconfig._app_opt_load()
    if lines is None:
      lines = {}
    lines[key] = value
    sysconfig._app_opt_save(lines)

  @staticmethod
  def getOption(key):
    lines = sysconfig._app_opt_load()
    if lines is None:
      lines = {}
    if key in lines:
      return lines[key]
    return None

  @staticmethod
  def removeOption(key):
    lines = sysconfig._app_opt_load()
    if lines is None:
      return
    lines.pop(key, False)
    sysconfig._app_opt_save(lines)

  @staticmethod
  def getHTTPAuth():
    user = None
    userfiles = ['/boot/http-auth.json', '/boot/firmware/http-auth.json', f'{path.CONFIGFOLDER}/http-auth.json']
    for userfile in userfiles:
      if os.path.exists(userfile):
        logging.debug(f'Found "{userfile}", loading the data')
        try:
          with open(userfile, 'r') as f:
            user = json.load(f)
            if 'user' not in user or 'password' not in user:
              logging.warning(f'"{userfile}" doesn\'t contain a user and password key')
              user = None
            else:
              break
        except Exception as e:
          logging.exception(f'Unable to load JSON from "{userfile}"')
          user = None
    return user

  @staticmethod
  def setHostname(name):
    # First, make sure it's legal
    name = re.sub(' ', '-', name.strip())
    name = re.sub(r'[^a-zA-Z0-9\-]', '', name).strip()
    if name == '' or len(name) > 63:
      return False

    # Next, let's edit the relevant files....
    with open('/etc/hostname', 'w') as f:
      f.write(f'{name}\n')

    lines = []
    with open('/etc/hosts', 'r') as f:
      for line in f:
        line = line.strip()
        if line.startswith('127.0.1.1'):
          line = f'127.0.1.1\t{name}'
        lines.append(line)
    with open('/etc/hosts.new', 'w') as f:
      for line in lines:
        f.write(f'{line}\n')

    try:
      os.rename('/etc/hosts', '/etc/hosts.old')
      os.rename('/etc/hosts.new', '/etc/hosts')
      # Keep the first version of the config.txt just-in-case
      os.unlink('/etc/hosts.old')

      # also, run hostname with the new name
      with open(os.devnull, 'wb') as void:
        subprocess.check_call(['/bin/hostname', name], stderr=void)

      # Final step, restart avahi (so it knows the correct hostname)
      try:
        with open(os.devnull, 'wb') as void:
          subprocess.check_call(['/usr/sbin/service', 'avahi-daemon', 'restart'], stderr=void)
      except subprocess.CalledProcessError:
        logging.exception('Couldnt restart avahi, not a deal breaker')
      return True
    except Exception as e:
      logging.exception('Failed to activate new hostname, you should probably reboot to restore')
    return False

  @staticmethod
  def getHostname():
    with open('/etc/hostname', 'r') as f:
      return f.read().strip()
